/**
 * Create two 1Claw agents (Alice and Bob) for the ECDH demo.
 *
 * 1Claw auto-generates per agent:
 *   - API key (ocv_...) for auth
 *   - Ed25519 SSH keypair for signing
 *   - P-256 ECDH keypair for key agreement
 *
 * Private keys are stored in the org's __agent-keys vault. This script
 * creates agents and grants each one read access to its own keys in
 * __agent-keys, then writes .env.ecdh.
 *
 * Requires: ONECLAW_API_KEY (your user API key), optionally ONECLAW_BASE_URL.
 *
 *   npm run ecdh:setup-agents
 *   cp .env.ecdh .env && npm run ecdh
 */

import { writeFileSync } from "fs";
import { createClient } from "@1claw/sdk";

const BASE_URL = process.env.ONECLAW_BASE_URL ?? "https://api.1claw.xyz";
const USER_API_KEY = process.env.ONECLAW_API_KEY;

const AGENT_KEYS_VAULT_NAME = "__agent-keys";

async function main() {
    if (!USER_API_KEY) {
        console.error("Set ONECLAW_API_KEY (your user API key). Optional: ONECLAW_BASE_URL");
        process.exit(1);
    }

    const client = createClient({ baseUrl: BASE_URL, apiKey: USER_API_KEY });

    console.log("Creating two agents (Alice and Bob)...");
    console.log("  (1Claw auto-generates Ed25519 + P-256 ECDH keys for each)\n");

    const aAliceRes = await client.agents.create({
        name: "Alice (ECDH demo)",
        description: "ECDH demo agent — key exchange with Bob",
        auth_method: "api_key",
    });
    const aBobRes = await client.agents.create({
        name: "Bob (ECDH demo)",
        description: "ECDH demo agent — key exchange with Alice",
        auth_method: "api_key",
    });
    if (aAliceRes.error || aBobRes.error) {
        console.error("Agent creation failed:", aAliceRes.error?.message ?? aBobRes.error?.message);
        process.exit(1);
    }
    const aliceAgent = aAliceRes.data!.agent;
    const bobAgent = aBobRes.data!.agent;
    const aliceApiKey = aAliceRes.data!.api_key;
    const bobApiKey = aBobRes.data!.api_key;
    if (!aliceApiKey || !bobApiKey) {
        console.error("Agent API keys not returned.");
        process.exit(1);
    }
    console.log(`  Alice: ${aliceAgent.id}`);
    console.log(`    ssh_public_key:  ${aliceAgent.ssh_public_key?.slice(0, 24)}...`);
    console.log(`    ecdh_public_key: ${(aliceAgent as Record<string, unknown>).ecdh_public_key?.toString().slice(0, 24)}...`);
    console.log(`  Bob:   ${bobAgent.id}`);
    console.log(`    ssh_public_key:  ${bobAgent.ssh_public_key?.slice(0, 24)}...`);
    console.log(`    ecdh_public_key: ${(bobAgent as Record<string, unknown>).ecdh_public_key?.toString().slice(0, 24)}...`);

    // Find __agent-keys vault and grant each agent read to its own keys
    const vaultsRes = await client.vaults.list();
    if (vaultsRes.error) {
        console.error("Failed to list vaults:", vaultsRes.error.message);
        process.exit(1);
    }
    const agentKeysVault = vaultsRes.data?.vaults?.find((v) => v.name === AGENT_KEYS_VAULT_NAME);
    if (!agentKeysVault) {
        console.error("__agent-keys vault not found. This org may not have any agents yet.");
        process.exit(1);
    }

    console.log("\nGranting each agent read access to its keys in __agent-keys...");
    const gAlice = await client.access.grantAgent(
        agentKeysVault.id,
        aliceAgent.id,
        ["read"],
        { secretPathPattern: `agents/${aliceAgent.id}/**` },
    );
    const gBob = await client.access.grantAgent(
        agentKeysVault.id,
        bobAgent.id,
        ["read"],
        { secretPathPattern: `agents/${bobAgent.id}/**` },
    );
    if (gAlice.error || gBob.error) {
        console.error("Grant failed:", gAlice.error?.message ?? gBob.error?.message);
        process.exit(1);
    }
    console.log("  Done.");

    const envLines = [
        "# ECDH demo — generated by npm run ecdh:setup-agents",
        "# Both agents use platform-generated keys (Ed25519 + P-256 ECDH).",
        "# Usage: cp .env.ecdh .env && npm run ecdh",
        "",
        `ONECLAW_BASE_URL=${BASE_URL}`,
        "",
        "# Alice (port 4100)",
        `ONECLAW_ALICE_AGENT_ID=${aliceAgent.id}`,
        `ONECLAW_ALICE_API_KEY=${aliceApiKey}`,
        "",
        "# Bob (port 4101)",
        `ONECLAW_BOB_AGENT_ID=${bobAgent.id}`,
        `ONECLAW_BOB_API_KEY=${bobApiKey}`,
        "",
    ];
    const envPath = new URL("../.env.ecdh", import.meta.url);
    writeFileSync(envPath, envLines.join("\n"), "utf8");
    console.log("\nWrote .env.ecdh");
    console.log("\nNext steps:");
    console.log("  cp .env.ecdh .env");
    console.log("  npm run ecdh");
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
